### PR TITLE
The Anti-Newline Quick Reaction Force has to be disbanded!

### PR DESCRIPTION
**Pull request by szepeviktor**
Just that.

### CODE REVIEW

**Comment by betterthanclay** [comment]
Hi Viktor.

The spacing in that class is there to distinguish related groups of methods to make it easier to read. Removing it only makes it harder to work with.

**Comment by szepeviktor** [comment]
Okay.

The Anti-Newline Quick Reaction Force was disbanded.

**Comment by betterthanclay** [comment]
Haha.. thanks for the input though!

**Comment by szepeviktor** [comment]
The normal answer would be to split up that huge class to several classes, traits, other OOP _tricks_.

**Pull request closed without merging**
